### ISSUE TITLE
Rabbitmq fails to be installed in Travis xenial

### ISSUE THREAD

**Issue by rporres** [smola/ci-tricks#19]
https://github.com/src-d/lookout uses ci-tricks throug `prepare-services` action in https://github.com/src-d/ci/blob/v1/Makefile.main

Current builds are broken due to
```
Failed to start rabbitmq-server.service: Unit rabbitmq-server.service not found.
error starting RabbitMQ: exit status 5
.ci/Makefile.main:261: recipe for target 'prepare-services' failed
make: *** [prepare-services] Error 1
The command "make ci-integration-dependencies" exited with 2.
```
which looks related to this repo

Related job log https://travis-ci.com/src-d/lookout/jobs/243370464

**Comment by smola** [comment]
Fixed in latest version: https://github.com/smola/ci-tricks/releases/tag/v0.2.0
